name: Build and Push Container Image On PR Comment

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  push-container-on-comment:
    name: push-registry-image
    if: contains(github.event.comment.body, '/build-and-push-container-image')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set env TAG for image
        run: |
          echo "TAG=pr-${{ github.event.pull_request.number }}" >> "$GITHUB_ENV"
      - name: Build Image to push
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: my-test-repo
          tags: ${{ env.TAG }}
          containerfiles: |
            ./Dockerfile
      - name: Push To Image Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/dbasunag
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Add comment to PR
        if: always()
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "Status of building tag ${{ env.TAG }}: ${{ steps.build-image.outcome }}. \nStatus of pushing tag ${{ env.TAG }} to image registry: ${{ steps.push-to-registry.outcome }}." }'
