name: Cherry Pick On Comment
on:
  issue_comment:
    types: [created]
jobs:
  cherry-pick:
    name: Cherry Pick
    if: |
      github.event.issue.pull_request != '' && contains(github.event.comment.body, '/cherry-pick')

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.OPENDATAHUB_TESTS_BOT_PAT }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Cherry Pick
        run: |
           echo ${{ github.event.comment.author_association }}
      - name: Automatic Cherry Pick
        if: |
          ((github.event.pull_request.author_association == 'CONTRIBUTOR') ||
          (github.event.pull_request.author_association == 'MEMBER') ||
          (github.event.pull_request.author_association == 'OWNER') ||
          (github.event.pull_request.author_association == 'COLLABORATOR')) 
        uses:  dbasunag/cherry-pick-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.OPENDATAHUB_TESTS_BOT_PAT }}
